# Generated by Django 4.2.6 on 2023-10-23 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_expensetracker_price'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExpenseTracker',
            new_name='Expense',
        ),
    ]
